/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'solar:home-2-outline',
      keepAlive: true,
      order: 1
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-history',
      i18nKey: 'route.chat-history',
      icon: 'solar:history-outline',
      order: 3
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'solar:heart-angle-outline',
      order: 4
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|register)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'shopping-cart',
    path: '/shopping-cart',
    component: 'layout.base$view.shopping-cart',
    meta: {
      title: 'shopping-cart',
      i18nKey: 'route.shopping-cart',
      icon: 'solar:cart-large-2-outline',
      order: 2
    }
  },
  {
    name: 'usage-monitor',
    path: '/usage-monitor',
    component: 'layout.base$view.usage-monitor',
    meta: {
      title: 'usage-monitor',
      i18nKey: 'route.usage-monitor',
      icon: 'solar:chart-2-line-duotone',
      roles: ['ADMIN'],
      order: 6,
      hideInMenu: true
    }
  }
];
